In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones(4)

array([1., 1., 1., 1.])

In [15]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
np.random.rand(5,5)

array([[0.85573134, 0.31974048, 0.8149284 , 0.10654484, 0.65056284],
       [0.51513462, 0.12268377, 0.81689988, 0.81469959, 0.23011292],
       [0.45434286, 0.57208487, 0.06689857, 0.9565418 , 0.73578375],
       [0.16884533, 0.96052863, 0.08064474, 0.24067929, 0.59655916],
       [0.63283402, 0.27348023, 0.10868479, 0.25016973, 0.26458442]])

In [20]:
np.random.randn(2)

array([-1.45347708,  0.31706936])

In [22]:
np.random.randint(1,100,10)

array([66, 16, 76, 45, 65, 10, 67, 61, 19, 97])

In [24]:
arr = np.arange(25)

In [25]:
ranarr = np.random.randint(0,50,10)

In [26]:
ranarr

array([19,  4, 37, 42, 13, 36, 32, 39, 44,  4])

In [27]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [28]:
ranarr

array([19,  4, 37, 42, 13, 36, 32, 39, 44,  4])

In [29]:
ranarr.max()

44

In [30]:
ranarr.min()

4

In [31]:
ranarr.argmax()

8

In [33]:
arr.shape

(25,)

In [34]:
arr.reshape(5,5).shape

(5, 5)

In [35]:
arr.dtype

dtype('int64')

In [36]:
import numpy as np

In [37]:
arr = np.arange(0,11)

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
arr[8]

8

In [40]:
arr[1:5]

array([1, 2, 3, 4])

In [41]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [42]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [43]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [44]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [45]:
arr[0:5] = 100

In [46]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [47]:
arr = np.arange(0,11)

In [48]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
slice_of_arr = arr[0:6]

In [50]:
slice_of_arr[:] = 99

In [51]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [52]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [53]:
arr_copy = arr.copy()

In [54]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [55]:
arr_copy[:] = 100

In [56]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [57]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [58]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [59]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [60]:
arr_2d[0][0]

5

In [62]:
arr_2d[0,0]

5

In [64]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [65]:
arr_2d[2:,1:]

array([[40, 45]])

In [66]:
arr = np.arange(1,11)

In [67]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
bool_array = arr > 5

In [70]:
bool_array

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [71]:
arr[bool_array]

array([ 6,  7,  8,  9, 10])

In [72]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [73]:
arr[arr<3]

array([1, 2])

In [74]:
arr_2d = np.arange(50).reshape(5,10)

In [75]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [77]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [79]:
import numpy as np

In [80]:
arr = np.arange(0,11)

In [81]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [82]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [87]:
arr/arr

/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in divide
  """Entry point for launching an IPython kernel.


array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [85]:
arr*9

array([ 0,  9, 18, 27, 36, 45, 54, 63, 72, 81, 90])

In [86]:
arr-100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [90]:
1./arr

/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [89]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [92]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [93]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [94]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [95]:
np.max(arr)

10

In [96]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [97]:
np.log(arr)

/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])